### ISSUE TITLE
Create README with master plan and how to each of the different python script interact with each other.

### ISSUE THREAD

**Issue by mflor35** [mflor35/Summer2015#15]
@kapilsinha already taking care of business.

**Comment by kapilsinha** [comment]
I did a preliminary version of this but feel free to change it (especially the second part because I just copied and pasted it from the first part). As for the actual master plan itself, I will work with Justin on stuff to take into account. He seems to know some of the basic info we will need to use - to be done with Zack after lunch.

**Comment by mflor35** [comment]
I will take look and update the information. Thank @kapilsinha !

**Comment by mflor35** [comment]
Master plan needs to be polished an put into a more readable format.

**Comment by kapilsinha** [comment]
Yes, but what file are you talking about? I don't think you have the master plan algorithm that I am working on.

**Comment by mflor35** [comment]
We did what we could.
